import whois as w
def scan_dominio():
    print("Iniciando o escaneamento do domínio...")
    print("----------------------------------------")
    print("|             WHOIS SCANNER            |")
    print("----------------------------------------")
    domain = input("Digite o domínio a ser escaneado:")
    print(f"Escaneando o domínio:{domain}")
    data = w.whois(domain)
    print(f"Domain: {data.domain_name}")
    print(f"Registrar: {data.registrar}")
    print(f"Registrar URL: {data.registrar_url}")
    print(f"Reseller: {data.reseller}")
    print(f"Whois Server: {data.whois_server}")
    print(f"Referral URL: {data.referral_url}")
    print(f"Updated Date: {data.updated_date}")
    print(f"Creation Date: {data.creation_date}")
    print(f"Expiration Date: {data.expiration_date}")
    print(f"Name Servers: {data.name_servers}")
    print(f"Status: {data.status}")
    print(f"Emails: {data.emails}")
    print(f"DNSSEC: {data.dnssec}")
    print(f"Name: {data.name}")
    print(f"Org: {data.org}")
    print(f"Address: {data.address}")
    print(f"City: {data.city}")
    print(f"State: {data.state}")
    print(f"Zipcode: {data.registrant_postal_code}")
    print(f"Country: {data.country}")
    print(f"Tech name: {data.tech_name}")
    print(f"Tech org: {data.tech_org}")
    print(f"Amin name: {data.admin_name}")
    print(f"Amin org: {data.admin_org}")
    return data

scanner = scan_dominio()
