import whois as w
def scan_dominio():
    print("Iniciando o escaneamento do domínio...")
    print("----------------------------------------")
    print("|             WHOIS SCANNER            |")
    print("----------------------------------------")
    domain = input("Digite o domínio a ser escaneado:")
    print(f"Escaneando o domínio:{domain}")
    data = w.whois(domain)
    print(f"Domain: {data.domain_name}\n")
    print("----------------------------------------")
    print(f"Registrar: {data.registrar}\n")
    print("----------------------------------------")
    print(f"Registrar URL: {data.registrar_url}\n")
    print("----------------------------------------")
    print(f"Reseller: {data.reseller}\n")
    print("----------------------------------------")
    print(f"Whois Server: {data.whois_server}\n")
    print("----------------------------------------")
    print(f"Referral URL: {data.referral_url}\n")
    print("----------------------------------------")
    print(f"Updated Date: {data.updated_date}\n")
    print("----------------------------------------")
    print(f"Creation Date: {data.creation_date}\n")
    print("----------------------------------------")
    print(f"Expiration Date: {data.expiration_date}\n")
    print("----------------------------------------")
    print(f"Name Servers: {data.name_servers}\n")
    print("----------------------------------------")
    print(f"Status: {data.status}\n")
    print("----------------------------------------")
    print(f"Emails: {data.emails}\n")
    print("----------------------------------------")
    print(f"DNSSEC: {data.dnssec}\n")
    print("----------------------------------------")
    print(f"Name: {data.name}\n")
    print("----------------------------------------")
    print(f"Org: {data.org}\n")
    print("----------------------------------------")
    print(f"Address: {data.address}\n")
    print("----------------------------------------")
    print(f"City: {data.city}\n")
    print("----------------------------------------")
    print(f"State: {data.state}\n")
    print("----------------------------------------")
    print(f"Zipcode: {data.registrant_postal_code}\n")
    print("----------------------------------------")
    print(f"Country: {data.country}\n")
    print("----------------------------------------")
    print(f"Tech name: {data.tech_name}\n")
    print("----------------------------------------")
    print(f"Tech org: {data.tech_org}\n")
    print("----------------------------------------")
    print(f"Admin name: {data.admin_name}\n")
    print("----------------------------------------")
    print(f"Admin org: {data.admin_org}\n")
    print("----------------------------------------")
    return data

scanner = scan_dominio()
